name: "[CI] Build"

on:
  push:
  pull_request:

env:
  RUBY_VERSION: 2.6.6

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres
    env:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: localhost

    steps:
      - uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 1

      - uses: ruby/setup-ruby@master
        with:
          ruby-version: ${{ env.RUBY_VERSION }}

      - name: Recover Ruby dependency cache
        uses: actions/cache@v1
        with:
          path: ./vendor/bundle
          key: ${{ runner.OS }}-rubydeps-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.OS }}-rubydeps-${{ env.cache-name }}-
            ${{ runner.OS }}-rubydeps-
            ${{ runner.OS }}-

      - name: Install Ruby deps
        run: |
          gem install bundler:2.1.4
          bundle install --path vendor/bundle --jobs 4 --retry 3

      - name: Lint and Rubocop
        run: |
          bundle exec rubocop
          # Disable erblint until we get to Decidim using 0.0.35. See
          # https://github.com/decidim/decidim/pull/6938 for details.
          #
          # bundle exec erblint app/{cells,views}/**/*.erb

      - name: Setup Database
        run: bundle exec rake test_app

      - name: Run RSpec
        run: COBERTURA=1 bundle exec rake

      - name: Codecov
        uses: codecov/codecov-action@v1
